### PR TITLE
Changed LoadDataWriter to load data in batches

### PR DESCRIPTION
**Pull request by AdalbertMemSQL**
This change will allow us to avoid table locking.
`insertBatchSize` config will be used to set batch size. Previously, we used it when `OnDuplicateKey` configuration was set.

### CODE REVIEW

**Comment by pmishchenko-ua** [comment]
With the default `insertBatchSize` of 10,000, can these changes negatively affect performance with default configuration? My guess is that at least 100,000 rows in batch are needed to get close to the best performance.

**Comment by AdalbertMemSQL** [comment]
> With the default `insertBatchSize` of 10,000, can these changes negatively affect performance with default configuration? My guess is that at least 100,000 rows in batch are needed to get close to the best performance.

I did perf testing with tests from this repo. Batch size showed the same performance. 100k may work bad for insert queries as there should be a limit for a statement length. I bumped into it with fivetran connector and update queries.

**Comment by AdalbertMemSQL** [comment]
We have a connection pool, so creating a new statement is just sending a small LOAD DATA query.

**Comment by pmishchenko-ua** [comment]
for insert queries 100k is indeed too much, I'm referring to LOAD DATA queries. You're saying that sending batches of 10k, , 100k, 1M rows shows the same performance?

**Comment by AdalbertMemSQL** [comment]
10k and 1m (no batches) show the same performance. Here queries are not parallelized (inside of one job), so 100k should also have the same performance.

**Comment by AdalbertMemSQL** [comment]
I checked several more parameters. `default_columnstore_table_lock_threshold` by default will lock all table rows if the query touches more than 5k rows https://docs.singlestore.com/cloud/create-a-database/columnstore/locking-in-columnstores/#overriding-default-locking so it makes sense to use even smaller batch size.

**Comment by AdalbertMemSQL** [comment]
Ignore my previous comment, it refers to rows per partition, so if there are at least 2 partitions - 10k should be ok :)

**Review by pmishchenko-ua — APPROVED** [review]

**Pull request merged**
